apiVersion: v2
name: pgpilot-operator
description: Kubernetes operator for declarative PostgreSQL monitoring via pgwatch
type: application
version: 0.1.1
appVersion: "1.0.1"
kubeVersion: ">=1.28.0-0"
home: https://github.com/jamalshahverdiev/pgpilot-operator
sources:
  - https://github.com/jamalshahverdiev/pgpilot-operator
maintainers:
  - name: Jamal Shahverdiyev
keywords:
  - postgresql
  - monitoring
  - pgwatch
  - observability
  - operator
